FROM openresty/openresty:1.15.8.2-7-bionic
LABEL name="www.datayang.com"
LABEL version="v1.0.0"
ENV name=datyang
ENV version=v1.0.0
COPY nginx.conf usr/local/openresty/nginx/conf/
EXPOSE 80
EXPOSE 443
EXPOSE 88
